### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gheorghina** [elixir-ecto/myxql#113]
Hello, 

When can we expect a new release for myxql with this fix: https://github.com/elixir-ecto/myxql/commit/082febbe5941a6e430680d5c133bc0e74469554d ?

The current memory leak is a bit pressing: https://github.com/elixir-ecto/ecto/issues/3311

Thank you.

**Comment by wojtekmach** [comment]
Done!

**Comment by gheorghina** [comment]
> Done!

thank you
