### ISSUE TITLE
How to close a connection to DB?

### ISSUE THREAD

**Issue by matthieuchabert** [elixir-ecto/myxql#121]
Hi,

We got an issue with our database connection (`Aborted connection`).

After creating a connection to our database with:
`{:ok, pid} = MyXQL.start_link()`

and then:
`MyXQL.query!(pid, query, [], [{:query_type, :text}])`

The connection was not disconnected when no longer used, even after `Process.exit(pid, :normal)`

Do you have some ideas on how to solve this?

**Comment by josevalim** [comment]
You can call `GenServer.stop(pid)` or `MyXQL.stop(pid)` if it exits. Note that no process terminates once they receive a `:normal` exit. You need to use `:shutdown` or another, but using the `stop` API is better!
