### ISSUE TITLE
No able to connect to TiDB

### ISSUE THREAD

**Issue by cleanyong** [elixir-ecto/myxql#133]
21:11:22.300 [error] GenServer #PID<0.241.0> terminating
** (stop) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :inet_tcp.getserv/1
        (kernel) inet_tcp.erl:55: :inet_tcp.getserv("4000")
        (kernel) gen_tcp.erl:176: :gen_tcp.connect1/4
        (kernel) gen_tcp.erl:163: :gen_tcp.connect/4
        (myxql) lib/myxql/client.ex:267: MyXQL.Client.do_connect/1
        (myxql) lib/myxql/client.ex:90: MyXQL.Client.connect/1
        (myxql) lib/myxql/connection.ex:32: MyXQL.Connection.connect/1
        (db_connection) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (kernel) gen_tcp.erl:168: :gen_tcp.connect/4
    (myxql) lib/myxql/client.ex:267: MyXQL.Client.do_connect/1
    (myxql) lib/myxql/client.ex:90: MyXQL.Client.connect/1
    (myxql) lib/myxql/connection.ex:32: MyXQL.Connection.connect/1
    (db_connection) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: MyXQL.Connection
** (Mix) The database for Hello.Repo couldn't be created: %RuntimeError{message: "killed"}

**Comment by hassan** [comment]
from [src](https://github.com/erlang/otp/blob/master/lib/kernel/src/inet_tcp.erl):

`getserv(Port) when is_integer(Port) -> {ok, Port};
`

**Comment by cleanyong** [comment]
My bad, after I changed from "4000" to 4000, it works! thanks a lot  :-)
