### ISSUE TITLE
Can we add command to Result to mirror Postgrex?

### ISSUE THREAD

**Issue by ivanovv** [elixir-ecto/myxql#137]
Looking at #26 and #27 can we add `command` to the `MyXQL.Result`?

That would help with Telemetry results being consistent.

**Comment by wojtekmach** [comment]
Do you know how Postgrex determines the command? Is it returned from the wire protocol or it is looking at the given SQL statement? I'd prefer to avoid the latter. Not sure if mysql server returns the information but if it does, a PR would be welcome.

**Comment by wojtekmach** [comment]
I'm going to close this for now, but some investigation and a PR would be appreciated. Thanks!

**Comment by greg-rychlewski** [comment]
For posterity, [Postgres returns a command tag in one of its messages](https://www.postgresql.org/docs/current/protocol-message-formats.html):

```
CommandComplete (B)

...

  The command tag. This is usually a single word that identifies which SQL command was completed.
  
  For an INSERT command, the tag is INSERT oid rows, where rows is the number of rows inserted. oid used to be the object ID of the inserted row if rows was 1 and the target table had OIDs, but OIDs system columns are not supported anymore; therefore oid is always 0.
  
  For a DELETE command, the tag is DELETE rows where rows is the number of rows deleted.
  
  For an UPDATE command, the tag is UPDATE rows where rows is the number of rows updated.
  
  For a SELECT or CREATE TABLE AS command, the tag is SELECT rows where rows is the number of rows retrieved.
  
  For a MOVE command, the tag is MOVE rows where rows is the number of rows the cursor's position has been changed by.
  
  For a FETCH command, the tag is FETCH rows where rows is the number of rows that have been retrieved from the cursor.
  
  For a COPY command, the tag is COPY rows where rows is the number of rows copied. (Note: the row count appears only in PostgreSQL 8.2 and later.)
```

And then [in MySQL it's returning this EOF packet](https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html) which doesn't have anything like that.
