### ISSUE TITLE
Compile time warning with db_connection 2.4.1: got "@impl true" for function checkin/1 but no behaviour specifies such callback

### ISSUE THREAD

**Issue by decius7bc** [elixir-ecto/myxql#141]
When compiling with [db_connection](https://github.com/elixir-ecto/db_connection) 2.4.1 a warning message gets generated:

```
warning: got "@impl true" for function checkin/1 but no behaviour specifies such callback. The known callbacks are:

  * DBConnection.checkout/1 (function)
  * DBConnection.connect/1 (function)
  * DBConnection.disconnect/2 (function)
  * DBConnection.handle_begin/2 (function)
  * DBConnection.handle_close/3 (function)
  * DBConnection.handle_commit/2 (function)
  * DBConnection.handle_deallocate/4 (function)
  * DBConnection.handle_declare/4 (function)
  * DBConnection.handle_execute/4 (function)
  * DBConnection.handle_fetch/4 (function)
  * DBConnection.handle_prepare/3 (function)
  * DBConnection.handle_rollback/2 (function)
  * DBConnection.handle_status/2 (function)
  * DBConnection.ping/1 (function)

  lib/myxql/connection.ex:63: MyXQL.Connection (module)
```

This may be caused by an [update to db_connection](https://github.com/elixir-ecto/db_connection/commit/f45f33267c88622777a3e8664d3b61f6c4820daf#diff-2b6c0f15240b4bb536845ad22714675c2bbcc86c11a7cb24ed1764d4bda1cc30) dropping the behaviour callback definition `DBConnection.checkin/1`.

**Comment by v0idpwn** [comment]
This if fixed in 893234cc97df9be3b764eba6e1706dd6dd6c3e9b, it just wasn't released yet

**Comment by savtrip** [comment]
Hey @wojtekmach is it possible to cut a new release to remove the warnings?

**Comment by wojtekmach** [comment]
v0.5.2 is out!

**Comment by savtrip** [comment]
Awesome thanks @wojtekmach, lightening fast! Also, thank you for all the open source work you do, it's much appreciated!

**Comment by wojtekmach** [comment]
Thank you for the kind words! <3
