### ISSUE TITLE
Stored Procedure Multi-Resultset

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-ecto/myxql#143]
Related to the discussion in https://github.com/elixir-ecto/myxql/issues/140.

Are you guys interested in returning multi-resultsets? My naive thinking is to return `[MyXQL.Result.t()]` from the relevant functions.

**Comment by wojtekmach** [comment]
Yes, I think we should support as many protocol features as possible. However, instead of existing functions return `Result.t | [Result.t]`, I'd consider introducing new functions like `MyXQL.query_many(...) :: [Result.t]`. WDYT? cc @josevalim

**Comment by josevalim** [comment]
query_many sounds good to me!

**Comment by greg-rychlewski** [comment]
Am I correct that this requires creating `query_many`/`execute_many` functions + handle callbacks in DBConnection?

Just want to make sure I don't create a mess before starting the PR.

**Comment by wojtekmach** [comment]
yeah, we'd need an `execute_many` too. We could have a `prepare_execute_many` for completeness, but let's hold off on that one for now. We don't need a new DBConnection callback, we'd change the existing one. Not sure if that's what you were asking.

**Comment by greg-rychlewski** [comment]
Oh sorry I meant that `MyXQL.execute`/`MyXQL.query` end up calling `DBConnection.execute` so was curious if you wanted `DBConnection.execute_many` with a `handle_execute_many` callback.

But it seems like you are saying we should specify an option that gets passed into `DBConnection.execute` so that the `handle_execute` callback can use it to decide if it should keep multiple results or error after the first one. Do I understand correctly?

**Comment by wojtekmach** [comment]
yeah, let's not change DBConnection, we should be able to do all the work in our callback implementation, the MyXQL.Connection.handle_execute function. You'll probably need to keep some state around in, well, `state`! (the last argument to all the callbacks)

**Comment by greg-rychlewski** [comment]
Will work on the PR :). Thanks!

**Comment by josevalim** [comment]
To be clear, I think the idea is that you send a different query struct to the usual execute/prepare callbacks, and that will lead to a different return type. Postgrex for example has more than struct it sends for querying.

**Comment by greg-rychlewski** [comment]
@josevalim I started playing around with it. Since `MyXQL.execute` returns `{:ok, query, result}` I'd have to expose the new struct. Is that okay? The only other alternatives I see are converting the new struct to a regular query struct at the end or using `opts` instead of a new struct.

**Comment by josevalim** [comment]
I think exposing the new struct is ok/expected.
