### ISSUE TITLE
Prepared statements exceeding limits when upgrading from 0.5 to 0.6

### ISSUE THREAD

**Issue by lucacorti** [elixir-ecto/myxql#147]
After upgrading to myxql 0.6 we saw prepared statemets constantly growing over time and exceeding the configured limit (16k)

![image](https://user-images.githubusercontent.com/1076999/150777871-a059205d-d4e1-4f1b-bd59-e1f0431e8bde.png)

while on 0.5 they are a small constant number

<img width="855" alt="Screenshot 2022-01-24 at 12 44 38" src="https://user-images.githubusercontent.com/1076999/150777891-9460a33e-eaee-46da-a089-915ca6807375.png">

**Comment by pierot** [comment]
We are experiencing the exact same.

**Comment by josevalim** [comment]
Thank you for the report. I am afraid [this commit](https://github.com/elixir-ecto/myxql/commit/2c97668c0c2a34bcea3665990f265a318b69e46d) introduced the issue. /cc @greg-rychlewski 

Can you please try running from commit: 1014f1c38421f1e0c93cc57a8e42c510cdd0e68c and see if the issue persists?

**Comment by greg-rychlewski** [comment]
Hi @pierot @lucacorti ,

Do you know if you are using prepared: :named or :unnamed? Thank you

**Comment by pierot** [comment]
@greg-rychlewski we don't have it set, so I guess it is `:named`?

**Comment by lucacorti** [comment]
@josevalim We'll try using that version.

@greg-rychlewski No, we are not setting any `prepared` configuration.

**Comment by greg-rychlewski** [comment]
@pierot @lucacorti Thanks and sorry one a couple other questions: 
- are you using Ecto with MyXQL adapter or MyXQL directly? 
    - if Ecto are you issuing them with Repo.all/Repo.one, etc or with Ecto.Adapters.SQL.query?
    - if MyXQL how are you calling the queries

**Comment by lucacorti** [comment]
@greg-rychlewski We are mostly using myxql via the Ecto adapter with Repo.all/one

**Comment by pierot** [comment]
@greg-rychlewski Only using Ecto with MyXQL adapter and Repo.all.

**Comment by lucacorti** [comment]
No, sorry, I was on the wrong node, still having problems with prepared statements growing indefinitely even with that version.

**Comment by josevalim** [comment]
@lucacorti @pierot can you please try master? I have reverted both commits that could have caused this.

**Comment by greg-rychlewski** [comment]
@josevalim I have an idea what the issue could be. But it's difficult for me to set up the environment needed right now. 

In multi-node setups prepared statements with the same name can be saved with different refs. If it was prepared on one node then executed in another. Before the cache change commit, it would just check for the name and not the ref. So the potential for re-preparing the same query was a lot smaller.

**Comment by lucacorti** [comment]
@josevalim  I'm running latest master in production, seems to behave like 0.5.2.

**Comment by josevalim** [comment]
Thank you! v0.6.1 is out!
