### ISSUE TITLE
Client-side prepared statements

### ISSUE THREAD

**Issue by heri16** [elixir-ecto/myxql#150]
Are client-side prepared statements supported? 

https://docs.singlestore.com/managed-service/en/developer-resources/connect-with-application-development-tools/using-prepared-statements.html

If yes, how can it be enabled? 
If no, what would be a good approach for a PR be like?

**Comment by josevalim** [comment]
This is the equivalent of using the :text encoding for queries but we don't have emulation. Emulating would be possible if implemented but I am a bit skeptical because parameters help everyone avoid SQL injection attacks, so it seems to be troublesome to disable this for performance(?) reasons.

**Comment by heri16** [comment]
Turning off binary protocol is not supported?

https://docs.singlestore.com/managed-service/en/connect-to-your-cluster/connect-with-mysql/connect-with-any-mysql-compatible-tool-to-singlestore.html

**Comment by wojtekmach** [comment]
As mentioned above you can use the text protocol with that option. There is no global option that would make all queries use text by default.
