### ISSUE TITLE
Please release a new version with issue 160 fixed

### ISSUE THREAD

**Issue by Sinc63** [elixir-ecto/myxql#170]
I'm upgrading to Elixir 1.14 and trying to resolve errors in dependencies. The error I am getting from myxql was fixed last November but hasn't been released. Would love to see it.

**Comment by wojtekmach** [comment]
there are not errors but warnings which don't halt the compilation (e.g. `mix compile --warnings-as-errors` does _not_ fail) right? In any case I can do a new release tomorrow.

**Comment by wojtekmach** [comment]
Done a while ago!
