### ISSUE TITLE
Telemetry support

### ISSUE THREAD

**Issue by yoonwaiyan** [elixir-ecto/myxql#179]
Hi, does myxql support telemetry out of the box? I've been trying to add Datadog APM to my project which currently uses MyXQL adapter but it doesn't receive any instrumentation from Ecto. Docs from ecto: https://hexdocs.pm/ecto/Ecto.Repo.html#module-adapter-specific-events, specifically this:

> Below we list all events developers should expect from Ecto. All examples below consider a repository named MyApp.Repo:
>
>`[:my_app, :repo, :query]`
>This event should be invoked on every query sent to the adapter, including queries that are related to the transaction management.

From here I'm expecting MyXQL as an adapter to fire out the telemetry `[:my_app, :repo, :query]` event which will be handled by [spandex_ecto](https://github.com/spandex-project/spandex_ecto) and send the log to Datadog, but I don't see any telemetry events being fired here within the adapter. 

Am I in the correct place to request for MyXQL to support telemetry? If not, can you point me out if there's already an existing telemetry being fired somewhere along a phoenix app?

**Comment by josevalim** [comment]
Yes, MyXQL will fire the event above (because it is fired by Ecto, not MyXQL). You should investigate spandex_ecto and explore why the event is not emitted. :)

**Comment by yoonwaiyan** [comment]
@josevalim thanks for the info, I managed to resolve the issue. The documentation was confusing which I thought each ecto adapter (in this case, MyXQL) needs to know how to fire the events.
