### ISSUE TITLE
How to configure ipv6 in `socket_options` ?

### ISSUE THREAD

**Issue by iagocavalcante** [elixir-ecto/myxql#182]
Found this issue when I try to deploy an Elixir/Phoenix API using MyXQL in a mysql database already in use for others APIs at fly. So I have some issues when deploy and I guess it because the `socket_options` used in the runtime. 

I clone this repo and made some tests, I can connect without `socket_options` locally but when I try to configure it I see some errors, first one is related to expected a keyword:

`{:ok, pid} = MyXQL.start_link(username: "root", password: "testpassword", hostname: "localhost", port: 3306, socket_options: [:inet6])`

![Captura de tela de 2024-05-18 11-31-04](https://github.com/elixir-ecto/myxql/assets/5131187/bb664f1c-8011-4d29-9eff-3cf7e4647cfe)

Then I tried put `[inet6: :inet6]` and thats the output:

![Captura de tela de 2024-05-18 11-32-22](https://github.com/elixir-ecto/myxql/assets/5131187/33ea7007-dee5-4290-9da6-1095c7c5465b)

Im trying to figure out how to connect using ipv6 with MyXQL, without `socket_options` works as expected

**Comment by josevalim** [comment]
Yeah, socket_options is not a keyword, so we should concat instead of merging.

**Comment by wojtekmach** [comment]
Fixed in #183.
