### ISSUE TITLE
pass check constraint error number 3819 / `ER_CHECK_CONSTRAINT_VIOLATED` as a `MyXQL.Error` server error code

### ISSUE THREAD

**Issue by petermueller** [elixir-ecto/myxql#186]
MySQL 8.0.16 added `ER_CHECK_CONSTRAINT_VIOLATED` which is signaled when a check constraint is violated.

https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_check_constraint_violated

This error code number does not seem to conflict with MariaDB (afaict)

**Comment by josevalim** [comment]
Closing in favor of the PR.
