### ISSUE TITLE
MyXQL not working fine with AWS aurora mysql 3 with write forwarding

### ISSUE THREAD

**Issue by teoortuno** [elixir-ecto/myxql#197]
I'm trying to connect to a global database in AWS RDS, whose type is Aurora MySQL 3, where one write cluster is in one region and one reader cluster is in another region. This means that every writing query is executed in the writer node, the data is replicated almost instantly in all reader nodes.

Then, in the reader node we have enabled write forwarding. This way, the writing queries are forwarded to the write node, and after it's executed in the writer node, it's replicated to all reader nodes.

I have tested this in several mysql clients and it works fine (including mysql-client, dbeaver, and some python drivers). But when I try to execute writing queries in the reader node with MyXQL, this is what happens:

1. the query is forwarded from the reader node to the writer node
2. after that, the query is executed in the writer node and replicated in the reader node
3. then, the RDS instance in the reader node attempts to restart the database, and then it restarts in mode read-only, and doesn't forward writes anymore until we reboot the instance.

This is my configuration:

mix.exs
```elixir
      {:myxql, "~> 0.7"},
```

config.exs
```elixir
config :project, Project.Repo, telemetry_prefix: [:project, :repo]
```

prod.exs
```elixir
config :project, Project.Repo,
  username: "dbuser",
  password: "password",
  database: "db",
  hostname: "host",
  pool_size: 20,
  queue_target: 1000
```

runtime.exs
```elixir
  if region != "eu-west-1" do
    # this is so the read replica in the US region can foward writes to EU region
    # check https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding-ams.html#aurora-global-database-write-forwarding-isolation-ams
    config :project, Project.Repo,
      after_connect: {MyXQL, :query!, ["SET aurora_replica_read_consistency = 'session'", []]}
  end
```

Any ideas?

**Comment by josevalim** [comment]
Most MySQL libraries are wrappers around the C package but our library implements the wire protocol. Probably the best thing to do is to use Wireshark and compare how writing to a write-replica and read-replica is different over the wire (using any library), and then make sure we deal with it in MyXQL. It may be that there is something different which we are not expecting.

**Comment by teoortuno** [comment]
After some research using Wireshark, I found that most mysql drivers don't use wire protocol like MyXQL does. But PHP's mysqli does use wire protocol in a similar way.

The thing is that when do queries with MyXQL, wire protocols are used for [preparing](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html) and [closing](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_close.html) statements.
But for other clients, the [query protocol](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_query.html) is used. 

With query protocol, everything works fine, but with prepared and close protocols, the server goes down.

It looks like a server problem, so I'm closing this. 

Nevertheless, I appreciate your help @josevalim, it helped to find the real problem.

**Comment by wojtekmach** [comment]
Thank you for the follow-up. We default to the binary protocol but you can control it via `query_type: :binary | :text` option, e.g.:

```elixir
MyXQL.query!(pid, "SELECT NOW()", [], query_type: :text)
```

I don't think we allow passing that option down from Ecto though so if that sounds like a solution we'd love a PR. Perhaps, when configuring repo for MyXQL adapter we'd allow :default_query_type option or something.

**Comment by teoortuno** [comment]
> Thank you for the follow-up. We default to the binary protocol but you can control it via `query_type: :binary | :text` option, e.g.:
> 
> ```elixir
> MyXQL.query!(pid, "SELECT NOW()", [], query_type: :text)
> ```
> 
> I don't think we allow passing that option down from Ecto though so if that sounds like a solution we'd love a PR. Perhaps, when configuring repo for MyXQL adapter we'd allow :default_query_type option or something.

Sure! We tried to do something like that and worked:

```elixir
MyXQL.query!(pid, "INSERT INTO user (email) VALUES 'test@example.com'", [], query_type: :text)
```

But we didn't go further because it crashes when we pass any parameters:
```elixir
> MyXQL.query!(pid, "INSERT INTO user (email) VALUES (?)", ["test@example.com"], query_type: :text)
** (ArgumentError) text queries cannot use parameters, got: ["test@example.com"]
    (myxql 0.7.1) lib/myxql/text_query.ex:21: DBConnection.Query.MyXQL.TextQuery.encode/3
    (db_connection 2.7.0) lib/db_connection.ex:1462: DBConnection.maybe_encode/4
    (db_connection 2.7.0) lib/db_connection.ex:823: DBConnection.execute/4
    (myxql 0.7.1) lib/myxql.ex:360: MyXQL.do_query/4
    (myxql 0.6.4) lib/myxql.ex:271: MyXQL.query!/4
```

It crashes [here](https://github.com/elixir-ecto/myxql/blob/9618d882e797a879d8f31eb4b475e6eab7ce7965/lib/myxql/text_query.ex#L21). Would be a bad idea if we also allow parameters on text queries? It looks like it's allowed by MySQL. What do you think?

**Comment by wojtekmach** [comment]
> It looks like it's allowed by MySQL. What do you think?

Looking at protocol description, https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_query.html, there are parameters but when I tried learning more about them it seems they are just for metadata used for logging, tracing, etc, not for sending values.

So yeah, does not seem to be supported:

```
mysql> select ?;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1
```

If the idea was MyXQL would automatically replace `?` with values given as parameters I believe this is very tricky due to escaping but more importantly seems out of the scope of the library given it is a pretty low level driver around the protocol. If the protocol does not support params and we need to do find-and-replace for `?`, you'd have to do that in your own code.
