### ISSUE TITLE
Add socket receive timeout when idle

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/myxql#38]
Currently the timeout is `:infinity` and cannot be configured. Since socket is always in passive mode this is OK for operations in client process, not OK for handshake which is connection process and it's actually not OK for ping because it's in connection process too.

Note it'd be an option on `MyXQL.start_link`, similar to Postgrex and Mariaex.

@josevalim @fishcakez should we mirror Postgrex in calling this `:timeout`? We have the following there:

> :timeout - Socket receive timeout when idle in milliseconds (default: 15000);

FWIW Mariaex has:

> :timeout - Connect timeout in milliseconds (default: 15000);

Or maybe we should have something more explicit like `:idle_timeout` (not to be confused with `:idle_interval` from dbconnection!)

**Comment by wojtekmach** [comment]
Worth mentioning that we have this in Ecto adapter:

- https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/mysql.ex#L29
- https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/mysql.ex#L313:L315

**Comment by fishcakez** [comment]
For `ping_timeout` I think it makes sense to implement this in dbconnection as this is issue faced by all drivers, it can work like after connect.

**Comment by wojtekmach** [comment]
@fishcakez sounds good.

Btw, do you think we should have a `connect_timeout` in DBConnection too? A caveat is Postgrex already has this option and it means a slightly different thing (socket connect timeout) and it has a `handshake_timeout` too, so we'd be replacing a fine grained timeouts with one coarse grained one.
