### ISSUE TITLE
MyXQL with Ecto: Error in MyXQL.Messages.decode_com_stmt_prepare_response when performing a SELECT

### ISSUE THREAD

**Issue by archdragon** [elixir-ecto/myxql#42]
## Description

I've decided to check how MyXQL+Ecto work with my staging DB. Error below appears each time I'm trying to select, via Repo.get, from any table. There are no errors when using `Ecto.Adapters.MySQL` (while still using `wojtekmach/ecto_sql`).

## How to reproduce
1. Use MyXQL with Ecto SQL:
  * in mix.exs set:
    ```
    {:myxql, "~> 0.1"},
    {:mariaex, ">= 0.0.0"},
    {:ecto_sql, github: "wojtekmach/ecto_sql", branch: "wm-myxql", override: true}
    ```
  * set adapter:
    `adapter: Ecto.Adapters.MyXQL`

2. Create a simple table and schema
    ```
    sql
    CREATE TABLE `dummy` (
      `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
      `name` varchar(100) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
    ```
    ```elixir
    defmodule Importer.Identity.Dummy do
      use Ecto.Schema

      schema "dummy" do
        field :name, :string
      end
    end
    ```

    ... and add some records

3. Run:
  ` Importer.Identity.Dummy |> Importer.Repo.get(1)`

   **-> Error Appears**

4. Switch adapter:
  `adapter: Ecto.Adapters.MySQL`

5. Run:
  ` Importer.Identity.Dummy |> Importer.Repo.get(1)`

   **-> No error - you get results back**

## Example error

```elixir
iex> Importer.Identity.User |> Importer.Repo.get(34)
```

### a) With Ecto.Adapters.MyXQL
```
  [debug] QUERY ERROR source="phpbb_users" db=112.7ms queue=44.9ms
  SELECT p0.`user_id`, p0.`username` FROM `phpbb_users` AS p0 WHERE (p0.`user_id` = ?) [34]
 ```

```
** (MatchError) no match of right hand side value: <<60, 0, 0, 5, 3, 100, 101, 102, 9, 110, 119, 100, 95, 115, 109, 111, 107, 105, 2, 112, 48, 11, 112, 104, 112, 98, 98, 95, 117, 115, 101, 114, 115, 8, 117, 115, 101, 114, 110, 97, 109, 101, 8, 117, 115, 101, 114, 110, 97, 109, ...>>
    (myxql) lib/myxql/messages.ex:380: MyXQL.Messages.decode_com_stmt_prepare_response/3
    (myxql) lib/myxql/protocol.ex:329: MyXQL.Protocol.recv_packets/4
    (myxql) lib/myxql/protocol.ex:682: MyXQL.Protocol.prepare/2
    (myxql) lib/myxql/protocol.ex:89: MyXQL.Protocol.handle_prepare/3
    (db_connection) lib/db_connection/holder.ex:270: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1180: DBConnection.prepare/4
    (db_connection) lib/db_connection.ex:1173: DBConnection.run_prepare/4
    (db_connection) lib/db_connection.ex:1185: DBConnection.run_prepare_execute/5
    (db_connection) lib/db_connection.ex:1282: DBConnection.run/6
    (db_connection) lib/db_connection.ex:504: DBConnection.parsed_prepare_execute/5
    (db_connection) lib/db_connection.ex:497: DBConnection.prepare_execute/4
    (ecto_sql) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.execute!/4
    (ecto_sql) lib/ecto/adapters/sql.ex:538: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.one/3
```

Displaying the list with `IO.puts` gives me
```
IO.puts([60, 0, 0, 5, 3, 100, 101, 102, 9, 110, ...)
<^@^@^E^Cdef    nwd_smoki^Bp0^Kphpbb_users^Husername^Husernam
```

where `nwd_smoki` is the DB(and DB User) name and `phpbb_users` is the table name.

### b) With Ecto.Adapters.MySQL

```
[debug] QUERY OK source="phpbb_users" db=51.5ms decode=16.6ms queue=44.2ms
SELECT p0.`user_id`, p0.`username` FROM `phpbb_users` AS p0 WHERE (p0.`user_id` = ?) [34]
```

```
%Importer.Identity.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "phpbb_users">,
  user_id: 34,
  username: "test"
}
```

### My DB, Table and Schema

* Error appears even with a very simple table/schema:

* The only unusual thing about my DB is the encoding (but error appears also when working with UTF-8 tables like the one above):
![image](https://user-images.githubusercontent.com/1810732/53109540-64ad5580-3539-11e9-8f21-39d6eb12ef6c.png)

**Comment by wojtekmach** [comment]
Thanks for the report. There were a few fixes since first release, could you try it on MyXQL master just in case this was already handled?

**Comment by archdragon** [comment]
Just cleaned the deps and added the MyXQL master. 

```
cat mix.lock | grep xql

"ecto_sql": {:git, "https://github.com/wojtekmach/ecto_sql.git","9a606732a30ae0ee29f5967d453f61a7b1afbdeb", [branch: "wm-myxql"]},
"myxql": {:git, "https://github.com/elixir-ecto/myxql.git", "a1351549d460b8994d60f700cc54b8bef7ceeadc", [branch: "master"]},
```

Unfortunately I'm still getting the same error.

**Comment by wojtekmach** [comment]
I've spoken with @archdragon and he's running MySQL 5.6.40 on Amazon RDS. Fortunately RDS supports other versions, but 5.6 is the default I believe. MySQL 5.6 does not support `CLIENT_DEPRECATE_EOF` capability flag which we're assuming (MySQL 5.7.10+ always sets that flag, and that's the minimal version we're targeting). I'll improve our handshake code to raise a decent error message when the server does not send that flag.
