### ISSUE TITLE
Add :json_library start_link option

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/myxql#44]
Currently we use application environment for this configuration, following Mariaex & Postgrex. If we're gonna do this, we could leave a deprecation warning for folks that were moving off Mariaex here.

Thoughts @josevalim?

**Comment by josevalim** [comment]
IIRC, We still need the config for other purposes in Ecto.SQL, so I would
keep it as an app environment.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
OK, I see it now, thanks!
