### ISSUE TITLE
Disconnect connection on `:closed` and similar tcp errors

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/myxql#49]

**Comment by fishcakez** [comment]
Should disconnect on *all* socket errors and return `DBConnection.ConnectionError`, not `MyXQL.Error`. I don't think there is a single socket error that we could handle and keep the connection alive. The different exception is pattern used by other drivers to differentiate between a transport error and a protocol error. `DBConnection` may return its own errors already, somewhat out of the control of `MyXQL`.

**Comment by wojtekmach** [comment]
@fishcakez perfect, thanks!
