### ISSUE TITLE
What's the key issue preventing 5.6 compatibility?

### ISSUE THREAD

**Issue by michaellenaghan** [elixir-ecto/myxql#50]
Amazon Aurora Serverless only supports MySQL 5.6. What's the key issue preventing 5.6 compatibility? (I'm trying to figure out whether or not adding compatibility is within my reach.)

**Comment by wojtekmach** [comment]
The main issue is we're not using deprecated eof packet which is advertised by enabling  `CLIENT_DEPRECATE_EOF` capability [1] which we do here [2]. There might be other incompatibilities, we haven't tested this on 5.6 at all, but I believe this is the only major one.

Feel free to give it a try, if it turns out supporting this version is straightforward then this will definitely make the library more useful. Make sure you target specific patch server version as the feature set tend to vary a lot. Btw, you'll probably run into this issue pretty early on: https://github.com/elixir-ecto/myxql/issues/42.

[1] https://dev.mysql.com/doc/internals/en/capability-flags.html#flag-CLIENT_DEPRECATE_EOF
[2] https://github.com/elixir-ecto/myxql/blob/v0.2.1/lib/myxql/protocol/messages.ex#L12

**Comment by michaellenaghan** [comment]
OK, thanks; I saw the CLIENT_DEPRECATE_EOF issue when I first looked into this, I just didn't know if there were other things I missed.

I'll close this and try to take a closer look over the next week or so.

**Comment by michaellenaghan** [comment]
Here's a first attempt, in patch form.

I'm sending a patch rather than a pull request for a few reasons. First, this is my attempt at a minimal patch; if I weren't trying to minimize the changes I'd take a somewhat different approach. (More on that below.) Second, I've only started looking at the code; I'm in that dangerous "I don't even know what I don't know" phase and I'm not convinced that I understand the response handling as well as I should. Third, I'm not set up to test this sufficiently well.

The main thing I'd do differently in a more invasive change would be to weave capabilities through the message processing. For example, I'd make the server capabilities available in the code that returns the client capabilities, and then I'd hang on to those server capabilities so that capability decisions could be made elsewhere.

```
diff --git a/lib/myxql/client.ex b/lib/myxql/client.ex
index f2c2e90..2dc6429 100644
--- a/lib/myxql/client.ex
+++ b/lib/myxql/client.ex
@@ -248,12 +248,8 @@ defmodule MyXQL.Client do
     recv_packet(&decode_initial_handshake/1, state)
   end
 
-  defp ensure_capabilities(initial_handshake(capability_flags: capability_flags)) do
-    if has_capability_flag?(capability_flags, :client_deprecate_eof) do
-      :ok
-    else
-      {:error, :server_not_supported}
-    end
+  defp ensure_capabilities(initial_handshake(capability_flags: _capability_flags)) do
+    :ok
   end
 
   defp send_handshake_response(
@@ -264,18 +260,22 @@ defmodule MyXQL.Client do
        ) do
     initial_handshake(
       auth_plugin_name: auth_plugin_name,
-      auth_plugin_data: auth_plugin_data
+      auth_plugin_data: auth_plugin_data,
+      capability_flags: capability_flags
     ) = initial_handshake
 
     auth_response = auth_response(auth_plugin_name, auth_plugin_data, config.password)
 
+    client_deprecate_eof? = has_capability_flag?(capability_flags, :capability_flags)
+
     payload =
       encode_handshake_response_41(
         config.username,
         auth_plugin_name,
         auth_response,
         config.database,
-        config.ssl?
+        config.ssl?,
+        client_deprecate_eof?
       )
 
     with :ok <- send_packet(payload, sequence_id, state) do
diff --git a/lib/myxql/protocol/messages.ex b/lib/myxql/protocol/messages.ex
index 355311e..0b22c59 100644
--- a/lib/myxql/protocol/messages.ex
+++ b/lib/myxql/protocol/messages.ex
@@ -6,10 +6,9 @@ defmodule MyXQL.Protocol.Messages do
 
   @max_packet_size 65536
 
-  defp capability_flags(database, ssl?) do
+  defp capability_flags(database, ssl?, client_deprecate_eof?) do
     put_capability_flags([
       :client_protocol_41,
-      :client_deprecate_eof,
       :client_plugin_auth,
       :client_secure_connection,
       :client_found_rows,
@@ -18,6 +17,7 @@ defmodule MyXQL.Protocol.Messages do
     ])
     |> maybe_put_capability_flag(:client_connect_with_db, !is_nil(database))
     |> maybe_put_capability_flag(:client_ssl, ssl?)
+    |> maybe_put_capability_flag(:client_deprecate_eof, client_deprecate_eof?)
   end
 
   defp maybe_put_capability_flag(flags, name, true), do: put_capability_flags(flags, [name])
@@ -70,6 +70,10 @@ defmodule MyXQL.Protocol.Messages do
     )
   end
 
+  def decode_generic_response(<<0xFE, num_warnings::uint2, status_flags::uint2>>) do
+    eof_packet(num_warnings: num_warnings, status_flags: status_flags)
+  end
+
   def decode_generic_response(
         <<0xFF, code::uint2, _sql_state_marker::string(1), _sql_state::string(5),
           message::binary>>
@@ -129,9 +133,10 @@ defmodule MyXQL.Protocol.Messages do
         auth_plugin_name,
         auth_response,
         database,
-        ssl?
+        ssl?,
+        client_deprecate_eof?
       ) do
-    capability_flags = capability_flags(database, ssl?)
+    capability_flags = capability_flags(database, ssl?, client_deprecate_eof?)
     auth_response = if auth_response, do: encode_string_lenenc(auth_response), else: <<0>>
     database = if database, do: <<database::binary, 0x00>>, else: ""
 
@@ -148,7 +153,7 @@ defmodule MyXQL.Protocol.Messages do
   end
 
   def encode_ssl_request(database) do
-    capability_flags = capability_flags(database, true)
+    capability_flags = capability_flags(database, true, false)
 
     <<
       capability_flags::uint4,
@@ -239,7 +244,7 @@ defmodule MyXQL.Protocol.Messages do
 
   # https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-COM_QUERY_Response
   def decode_com_query_response(<<header, rest::binary>>, "", :initial)
-      when header in [0x00, 0xFF] do
+      when header in [0x00, 0xFE, 0xFF] do
     {:halt, decode_generic_response(rest, header)}
   end
 
@@ -313,7 +318,7 @@ defmodule MyXQL.Protocol.Messages do
 
   # https://dev.mysql.com/doc/internals/en/com-stmt-execute-response.html
   def decode_com_stmt_execute_response(<<header, rest::binary>>, "", :initial)
-      when header in [0x00, 0xFF] do
+      when header in [0x00, 0xFE, 0xFF] do
     {:halt, decode_generic_response(rest, header)}
   end
 
diff --git a/lib/myxql/protocol/records.ex b/lib/myxql/protocol/records.ex
index f4306eb..81c92c1 100644
--- a/lib/myxql/protocol/records.ex
+++ b/lib/myxql/protocol/records.ex
@@ -6,6 +6,9 @@ defmodule MyXQL.Protocol.Records do
   # https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html
   defrecord :ok_packet, [:affected_rows, :last_insert_id, :status_flags, :num_warnings, :info]
 
+  # https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html
+  defrecord :eof_packet, [:num_warnings, :status_flags]
+
   # https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html
   defrecord :err_packet, [:code, :message]
```

**Comment by michaellenaghan** [comment]
I think I missed one case around [`decode_com_stmt_prepare_response`](decode_com_stmt_prepare_response), related to [14.7.4.1 `COM_STMT_PREPARE` Response](https://dev.mysql.com/doc/internals/en/com-stmt-prepare-response.html#packet-COM_STMT_PREPARE_OK); notice that if `num_params` or `num_columns` is greater than zero an [`EOF Packet`](https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html) is sent.

**Comment by wojtekmach** [comment]
@michaellenaghan thank you, this a really good start and I'm cautiously optimistic we can support 5.6 without complicating things too much.

You're right that we'd need to hold on to server capabilities so that we would re-use them elsewhere. What we'd need to do is add it to structs and keep them in connection state [here](https://github.com/elixir-ecto/myxql/blob/v0.2.1/lib/myxql/connection.ex#L13) and [here](https://github.com/elixir-ecto/myxql/blob/v0.2.1/lib/myxql/client.ex#L11)

Did you manage to run tests against 5.6 and 5.7?

For me, against 5.7 all except a couple passed so this is a really good sign. Against 5.6 I was able to connect but could run neither text nor binary query.

If you have docker installed you can test against different DB versions like this:

```
MYSQL_TCP_PORT=9999 DB=mysql:5.6 ./ci.sh test/myxql_test.exs
# (if you skip the port env var, the container will bind to the default port 3306)
```

**Comment by michaellenaghan** [comment]
Sorry, I misunderstood the instructions for running the Docker-based tests; I'll try to take a look next week. Thanks!

**Comment by michaellenaghan** [comment]
I won't pursue this right now; the bugs I just logged are a result of my taking a closer look. I think that in order to fix this properly some of those bugs would have to be dealt with. For example, capability negotiation would have to be done correctly, and the client would need to remember what was negotiated. (My quick and dirty implementation tried to be "stateless". I already thought that was pushing things. Now I'm even more convinced it was a mistake; it would bury non-standard behaviour in an already complicated implementation and make life more difficult for maintainers.)

**Comment by wojtekmach** [comment]
@michaellenaghan thanks for submitting these issues, they're definitely steps in the right direction.

**Comment by michaellenaghan** [comment]
I realized there's another option here that would very likely work with the current implementation: don't support client_deprecate_eof.

If you supported client_session_track you wouldn't have that option, but [you don't](https://github.com/elixir-ecto/myxql/blob/a3a0384fd56625523c73f43e02802307bd5e6c89/lib/myxql/protocol/messages.ex#L13), so you do.

Thoughts?

(Again, from my perspective the primary goal is support for older servers. Or, at least, 5.6 servers.)

**Comment by wojtekmach** [comment]
> I realized there's another option here that would very likely work with the current implementation: don't support client_deprecate_eof.

@michaellenaghan yup, that was a great idea and that's exactly what I did on master. We can always bring back that capability when we do support session tracking.

I have passing tests against MySQL 5.6 (and 5.5!) so I'm gonna close this for now. There's always more compatibility work to potentially do, e.g. supporting old password authentication scheme, but since that's insecure I don't plan to. If you find any incompatibilities please let us know.

And thank you so much for this and related tickets, that has been great help!
