### ISSUE TITLE
Server can send an ERR packet rather than an Initial Handshake Packet

### ISSUE THREAD

**Issue by michaellenaghan** [elixir-ecto/myxql#52]
The code [here](https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/client.ex#L238) assumes that the server will always send an initial handshake packet, but as documented [here](https://dev.mysql.com/doc/internals/en/connection-phase.html) the server might send an ERR packet instead. 

As the page notes, an initial ERR packet will be sent before capabilities are negotiated and therefore won't include the conditional `server_state` fields.

**Comment by wojtekmach** [comment]
Good catch, thank you. I was able to reproduce this by setting:

```sql
set global max_connections = 1;
```

and starting a couple connections.
