### ISSUE TITLE
The code in recv_packets doesn't verify the sequence_id

### ISSUE THREAD

**Issue by michaellenaghan** [elixir-ecto/myxql#53]
The code [here](https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/client.ex#L161) ignores rather than verifies the `sequence_id`.

**Comment by wojtekmach** [comment]
Yes, we've opened a similar issue, https://github.com/elixir-ecto/myxql/issues/36, but we've decided for now to ignore the sequence and instead rely on the servers (and underlying TCP protocol) to return packets in order.

**Comment by michaellenaghan** [comment]
I think that's a mistake. The sequence isn't there as a check on the server, it's there as a check that the server and client are in agreement about their conversation.

By not checking the sequence certain bugs will just be harder to spot.
