### ISSUE TITLE
The implementation of sha256_password appears to be wrong

### ISSUE THREAD

**Issue by michaellenaghan** [elixir-ecto/myxql#54]
[Here](https://github.com/elixir-ecto/myxql/blob/f454eaaac9602642dc35f3f20163bc15d459659c/lib/myxql/client.ex#L270) the handshake code appears to take the `auth_plugin_data` from the initial handshake and pass it into `auth_response`. For `sha256_password` and `caching_sha2_password`, `auth_response` then passes that data into `sha256_password` [here](https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/protocol/auth.ex#L13). 

As far as I can tell, that isn't right. [Here](https://dev.mysql.com/doc/internals/en/sha256.html) are the docs for [`sha256_password`](sha256_password). They say:

> If the password is non-empty SHA256 auth method
>
> * XORs the clients password with the scramble buffers content
>
> * RSA encrypts that with the server's public key using RSA_PKCS1_OAEP_PADDING as padding
>
> Empty passwords are not hashed, but sent as empty string.

It appears that the client is either expected to already have the public key or to ask for it. [Here](https://dev.mysql.com/doc/internals/en/public-key-retrieval.html) the docs explain how to ask for it. When asked the server sends the key in an `AuthMoreData` packet; I don't think MyXQL implements that?

The docs have worked examples of `sha256_password ` logins [here](https://dev.mysql.com/doc/internals/en/sha256-example.html).

**Comment by michaellenaghan** [comment]
Btw, note the special treatment of empty passwords.

**Comment by wojtekmach** [comment]
I wouldn't say the implementation is wrong, but it's definitely incomplete. From [SHA256 Example](https://dev.mysql.com/doc/internals/en/sha256-example.html) link, we implement "fast path" and "not so fast path", but only when the connection is using SSL. See tests tagged with `auth_plugin: "sha256_password"` in https://github.com/elixir-ecto/myxql/blob/master/test/myxql_test.exs. But yes, we should definitely support this on insecure connection too.

**Comment by michaellenaghan** [comment]
Is it possible there's an error with the test? The docs say that the `sha256_password` method:

> RSA encrypts that with the server's public key using RSA_PKCS1_OAEP_PADDING as padding

and the [current implementation](https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/protocol/auth.ex#L13) doesn't do anything like that. By way of comparison, [here](https://github.com/mysql/mysql-connector-j/blob/36534fa273b4d7824a8668ca685465cf8eaeadd9/src/main/protocol-impl/java/com/mysql/cj/protocol/a/authentication/Sha256PasswordPlugin.java) is the Java implementation of `sha256_password` in the client.

**Comment by michaellenaghan** [comment]
OK, I think I finally understand. Here's the code:

```
  defp auth_response(plugin_name, plugin_data, password)
       when plugin_name in ["sha256_password", "caching_sha2_password"],
       do: Auth.sha256_password(password, plugin_data)

  ...

  defp auth_switch_response(plugin_name, password, _plugin_data, ssl?)
       when plugin_name in ["sha256_password", "caching_sha2_password"] do
    if ssl? do
      {:ok, password <> <<0x00>>}
    else
      auth_plugin_secure_connection_error(plugin_name)
    end
  end
```

For `sha256_password` if the connection is using SSL then the code sends a cleartext password in `auth_switch_response`. That's OK. But the fast path—which I believe would only be called if `sha256_password` was the default authentication—runs the password through `Auth.sha256_password`. I think that's wrong.
