### ISSUE TITLE
The implementation of the capability negotiation appears to be wrong

### ISSUE THREAD

**Issue by michaellenaghan** [elixir-ecto/myxql#55]
According to the [docs](https://dev.mysql.com/doc/internals/en/capability-negotiation.html):

> The client should only announce the capabilities in the Handshake Response Packet that it has in common with the server.

In effect, in the response packet the client should `AND` its capabilities with the server's.

Instead, [here](https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/protocol/messages.ex#L127), the client is just announcing its own capabilities.

**Comment by wojtekmach** [comment]
Good catch, for now I change the code so that we return an error if the server doesn't support all capabilities we currently require. As we support older server versions we will inevitably have to do proper capability negotiation. I'm gonna close this for now.
