### ISSUE TITLE
cannot use with ProxySQL

### ISSUE THREAD

**Issue by chulkilee** [elixir-ecto/myxql#58]
I found that my app is talking to mysql via ProxySQL, myxql could not connect to the database, while mariaex could.

### Background

- ecto URL: `ecto://username:password@127.0.0.1:3136/dbname?pool_size=15`
- the database user has minimal read-only access and requires "mysql_native_password"
- the endpoint is behind of ProxySQL (1.4.12 from [severalnines/proxysql](https://hub.docker.com/r/severalnines/proxysql))
- mysql server (behind proxysql): 8.0.11

Deps

- ecto: 3.1.4
- ecto_sql: 3.1.1
- myxql: d5b4d8beddca4f0eaad7799a98e4b49c37c7a8e5

Output of `SHOW VARIABLES LIKE "%version%";` from Sequel Pro

```
innodb_version	8.0.11
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1,TLSv1.2
version	8.0.11
version_comment	MySQL Community Server - GPL
version_compile_machine	x86_64
version_compile_os	Linux
version_compile_zlib	1.2.11
```

When connected with mysql CLI:

```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Server version: 8.0.11 (ProxySQL)
```

Error:

```
10:55:04.639 [error] MyXQL.Connection (#PID<0.361.0>) failed to connect: ** (MyXQL.Error) MyXQL requires MySQL server 5.7.10+
```

If I made the app directly talk to mysql slave (not via ProxySQL), it works well :)

I'm not sure whether it's our ProxySQL configuration issue, or ProxySQL actually does not support some features. Still investigating..

**Comment by wojtekmach** [comment]
Thanks for the report! Could you try master? It should now report which server capability is missing. I suspect `client_deprecate_eof` is missing and we're planning to gracefully handle that (#50)

We've recently added some utilities to test this driver across different databases versions ([`docker-compose.yml`](https://github.com/elixir-ecto/myxql/blob/master/docker-compose.yml), [`scripts/test-versions.sh`](https://github.com/elixir-ecto/myxql/blob/master/scripts/test-versions.sh)), if you're able to use these tools to reproduce the error and document them here I'd be happy to investigate this further, I'm not familiar with proxysql yet!

**Comment by chulkilee** [comment]
Tested with ProxySQL 1.4.15 and 2.0.4, and myxql (138df8cc2ab6f4a00690634352e975a3360dd9bc) failed to connect to both.Tested with ProxySQL 1.4.15 and 2.0.4, and myxql failed to connect to both.

Both failed with following error (passing `show_sensitive_data_on_connection_error: true` to `MyXQL.start_link/1`).

```
[error] GenServer #PID<0.541.0> terminating
** (RuntimeError) server does not support :client_deprecate_eof capability
    (myxql) lib/myxql/protocol/messages.ex:124: MyXQL.Protocol.Messages.ensure_capability!/2
    (myxql) lib/myxql/protocol/messages.ex:149: anonymous fn/3 in MyXQL.Protocol.Messages.build_capability_flags/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (myxql) lib/myxql/protocol/messages.ex:148: MyXQL.Protocol.Messages.build_capability_flags/2
    (myxql) lib/myxql/client.ex:247: MyXQL.Client.do_handshake/2
    (myxql) lib/myxql/client.ex:232: MyXQL.Client.handshake/2
    (myxql) lib/myxql/connection.ex:33: MyXQL.Connection.connect/1
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
```

I also ran `MYSQL_TCP_PORT=6033 mix test` to test myxql with proxysql, and most test failed with the same error. There are several exceptions:

```
 79) test prepared queries prepare and then execute (MyXQLTest)
     test/myxql_test.exs:206
     ** (EXIT from #PID<0.487.0>) killed


11:33:24.901 [error] GenServer #PID<0.494.0> terminating
** (MyXQL.Error) (1049) (ER_BAD_DB_ERROR) Unknown database 'myxql_test'
    (db_connection) lib/db_connection/connection.ex:84: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: MyXQL.Connection

 85) test connect connect with bad SSL opts (MyXQLTest)
     test/myxql_test.exs:9
     Assertion with =~ failed
     code:  assert capture_log(fn ->
              opts = Keyword.merge(@opts, ssl: true, ssl_opts: [ciphers: [:bad]])
              assert_start_and_killed(opts)
            end) =~ "** (DBConnection.ConnectionError) Invalid TLS option: {ciphers,[bad]}"
     left:  "\e[31m\n11:33:24.929 [error] GenServer #PID<0.525.0> terminating\n** (DBConnection.ConnectionError) :server_does_not_support_ssl\n    (db_connection) lib/db_connection/connection.ex:84: DBConnection.Connection.connect/2\n    (connection) lib/connection.ex:622: Connection.enter_connect/5\n    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\nLast message: nil\nState: MyXQL.Connection\n\e[0m"
     right: "** (DBConnection.ConnectionError) Invalid TLS option: {ciphers,[bad]}"
     stacktrace:
       test/myxql_test.exs:10: (test)

 97) test query binary: query with multiple rows (MyXQLTest)
     test/myxql_test.exs:173
     ** (EXIT from #PID<0.576.0>) killed


11:33:24.966 [error] GenServer #PID<0.583.0> terminating
** (MyXQL.Error) (1049) (ER_BAD_DB_ERROR) Unknown database 'myxql_test'
    (db_connection) lib/db_connection/connection.ex:84: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: MyXQL.Connection
```


I'm not sure proxysql does not return response, or return response but "not supported".

**Comment by wojtekmach** [comment]
Thanks for validating this! MySQL 5.6 compatibility is my next priority and it should solve this issue as well.

**Comment by chulkilee** [comment]
Please note that when I run `SHOW VARIABLES LIKE "%version%";`, ProxySQL instance returns the mysql version behind of it - in my case 8.0.11.

I don't know 1) what each flag means, and 2) how ProxySQL works in details... but it seems like at least a ProxySQL issue, if it doesn't handle the flag same with the backend mysql server.

**Comment by wojtekmach** [comment]
It should now work on master, please give it a try!

**Comment by chulkilee** [comment]
Great! I tested fb802414cece2e8c304d0a46de3cfd32494f38bf and it worked - I guess bdbb5edf680411e66c7571b7efa31327c268aff3 fixed it.

Closing it as it works :clap:
