### ISSUE TITLE
utf8_general_ci vs utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by michaelst** [elixir-ecto/myxql#59]
If there isn't going to be an option to change the charset why not choose one that is more up to date? utf8 (utf8mb3 in mysql) is now deprecated and utf8mb4 also allows for emojis. Numerous sources also point to unicode being a better option than general. Are there any limitations or reasons that explain why utf8_general_ci was chosen?

Is the comment in this issue (https://github.com/elixir-ecto/myxql/issues/40) a workaround to the MARIAEX compatibility problem for not being able to set charset?

**Comment by wojtekmach** [comment]
We already default to utf8mb4 on master!

**Comment by michaelst** [comment]
That's great, this file should be updated then https://github.com/elixir-ecto/myxql/blob/master/MARIAEX_COMPATIBILITY.md

**Comment by wojtekmach** [comment]
Good catch, fixed on master.
