### ISSUE TITLE
Incompatibility with Mariaex for users with empty password

### ISSUE THREAD

**Issue by danxexe** [elixir-ecto/myxql#63]
Mariaex behaviour:

```elixir
iex> {:ok, pid} = Mariaex.start_link(username: "user", password: "", database: "app_test")
{:ok, #PID<0.400.0>}
```

MyXQL behaviour:

```elixir
iex> {:ok, pid} = MyXQL.start_link(username: "user", password: "", database: "app_test")
{:ok, #PID<0.408.0>}
19:11:08.187 [error] MyXQL.Connection (#PID<0.410.0>) failed to connect: ** (MyXQL.Error) (1045) (ER_ACCESS_DENIED_ERROR) Access denied for user 'user'@'localhost' (using password: YES)
```

Using `nil` as password works as expected:

```elixir
iex> {:ok, pid} = MyXQL.start_link(username: "user", password: nil, database: "app_test")
{:ok, #PID<0.416.0>}
```

One of the issues with this incompatibility is that it breaks using urls when configuring a repo with ecto since ecto will parse the password as an empty string for such cases:

```elixir
iex> Ecto.Repo.Supervisor.parse_url("mysql://user:@127.0.0.1:3306/app_test")
[
  username: "user",
  password: "",
  database: "app_test",
  hostname: "127.0.0.1",
  port: 3306
]
```

The obvious workaround is to simply not use `url` and use `password: nil` instead when configuring a repo.

This behaviour is a bit surprising, I believe it should be either fixed or at least [documented here](https://github.com/elixir-ecto/myxql/blob/master/MARIAEX_COMPATIBILITY.md).

**Comment by wojtekmach** [comment]
> `iex> Ecto.Repo.Supervisor.parse_url("mysql://user:@127.0.0.1:3306/app_test")`
> The obvious workaround is to simply not use url and use password: nil instead when configuring a repo.

Passing the url as `"mysql://user@127.0.0.1:3306/app_test"` (without specifying password) would work too.

I think it makes sense to transform password `""` into `nil`, will work on a patch.

**Comment by danxexe** [comment]
> Passing the url as "mysql://user@127.0.0.1:3306/app_test" (without specifying password) would work too.
Didn't think of that 🤦‍♂.

> I think it makes sense to transform password "" into nil, will work on a patch.
Cool, it's probably best to keep it as compatible as possible with mariaex.
