### ISSUE TITLE
Ecto Stream Errors

### ISSUE THREAD

**Issue by k-cross** [elixir-ecto/myxql#64]
I might not understand something related to Ecto streams and transactions but this code was working with `mariaex`. I've distilled the base case down to this code in order to reproduce it. Basically I always receive an error tuple when I expect an ok tuple as a response. Please let me know if there is anything else I can help you with, sorry if this is not enough info.

https://gist.github.com/k-cross/c3a0bb2a2c6b32ae0da548e9b634b63b

**Comment by wojtekmach** [comment]
Thanks for the report, unfortunately I'm not able to reproduce this locally.
By always returning error tuple, do you mean the transaction is always rolled back? If you remove the `rescue` clause, what's the exception being raised?

Another way to move this forward would be to create a small repo that reproduces the issue with a script/test? You can use this repo as a starting point: https://github.com/wojtekmach/ecto_example

**Comment by k-cross** [comment]
Okay, I will create the sample project to move forward. Yes, this kept producing roll backs. I just get `%ArgumentError{message: "argument error"}`.

**Comment by wojtekmach** [comment]
What is the stacktrace for the ArgumentError?

**Comment by k-cross** [comment]
Sorry to lead you down a bad path, this was a `Jason` decoding issue. There still might be a difference in how this is handled but I'll diagnose that issue further. Thank you for your help!

**Comment by wojtekmach** [comment]
No worries!
