### ISSUE TITLE
Zero dates/datetimes in data raises exception

### ISSUE THREAD

**Issue by sebastiw** [elixir-ecto/myxql#65]
After https://github.com/elixir-ecto/myxql/commit/425550de2aa97243b4158ff685225b6ff478269b
zero dates and datetimes raises ArgumentError.
This make it impossible to get data from queries where zero dates exist.

Imagine the scenario where there exist a column in a table where a couple of rows have zero dates stored.
The user application that runs the query will then fail and no data would be retrieved if it includes one of the rows with zero date.

I own a service with legacy code that have a MySQL database with default values of "0000-00-00".
This service allows some arbitrary queries to be run from a couple of other services.
These dependent services will now fail because my service can't return any data. It would be ok if I could just catch and replace that value, but I can't at the moment. IMO it should be up to the user of MyXQL to decide what to do when a zero date is encountered.

**Comment by wojtekmach** [comment]
Fixed in #66.
