### ISSUE TITLE
Fetching Datetime fields causes `FunctionClauseError`

### ISSUE THREAD

**Issue by seunm** [elixir-ecto/myxql#72]
I have a table that stores datetime values. I can store data fine but I keep getting `FunctionClauseError` thrown when i try to retrieve the data. The docs say that even though the data is represented as [NaiveDateTime](https://hexdocs.pm/elixir/NaiveDateTime.html), that one should still be able to use [DateTime](https://hexdocs.pm/elixir/DateTime.html) but it doesn't work. 
Error: 
`** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.decode_datetime/5

    The following arguments were given to MyXQL.Protocol.Values.decode_datetime/5:

        # 1
        <<0, 7, 226, 7, 8, 10, 21, 45, 0>>

        # 2
        0

        # 3
        [:naive_datetime]

        # 4
        [~N[2018-08-10 09:25:11], nil, 296, 2097152, 169544, 946454680]

        # 5
        :naive_datetime

    Attempted function clauses (showing 3 out of 3):

        defp decode_datetime(-<<4::integer(), year::integer()-little()-size(16), month::integer()-size(8), day::integer()-size(8), r::bitstring()>>-, null_bitmap, t, acc, type)
        defp decode_datetime(-<<7::integer(), year::integer()-little()-size(16), month::integer()-size(8), day::integer()-size(8), hour::integer()-size(8), minute::integer()-size(8), second::integer()-size(8), r::bitstring()>>-, null_bitmap, t, acc, type)
        defp decode_datetime(-<<11::integer(), year::integer()-little()-size(16), month::integer()-size(8), day::integer()-size(8), hour::integer()-size(8), minute::integer()-size(8), second::integer()-size(8), microsecond::integer()-little()-size(32), r::bitstring()>>-, null_bitmap, t, acc, type)

    (myxql) lib/myxql/protocol/values.ex:417: MyXQL.Protocol.Values.decode_datetime/5
    (myxql) lib/myxql/protocol.ex:517: MyXQL.Protocol.decode_resultset/4
    (myxql) lib/myxql/client.ex:173: MyXQL.Client.recv_packets/5
    (myxql) lib/myxql/connection.ex:97: MyXQL.Connection.handle_execute/4
    (db_connection) lib/db_connection/holder.ex:277: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:540: DBConnection.parsed_prepare_execute/5`

I'm using MyXQL with Ecto and this is how my schema is represented

`schema "xx" do
    ...
    field :created_at, :utc_datetime
    field :updated_at, :utc_datetime
    field :resolved_at, :utc_datetime
    ...`

where `:utc_datetime` maps to Elixir's [DateTime](https://hexdocs.pm/elixir/DateTime.html)

Happy to help anyway I can. Thanks

**Comment by wojtekmach** [comment]
quick question, what's your myxql version?

**Comment by seunm** [comment]
0.2.0

**Comment by wojtekmach** [comment]
could you try against the latest version?

**Comment by seunm** [comment]
isn't that the latest version. thats what the readme says

**Comment by wojtekmach** [comment]
The latest version is v0.2.6

**Comment by seunm** [comment]
alright. will give it a try

**Comment by seunm** [comment]
Thanks that fixed it!

**Comment by wojtekmach** [comment]
Great!
