### ISSUE TITLE
Test suite failing with "Illegal mix of collations" errors

### ISSUE THREAD

**Issue by dbhobbs** [elixir-ecto/myxql#74]
I'm migrating from `mariaex` to `myxql` and our test suite is throwing a large number of collation errors. The two columns used in the query are an `varchar(255)` and a `binary(16)` (an `Ecto.UUID` type field). The collations are all set to `utf8mb4_unicode_ci`, which is also what is set in the Repo config.

This is the error received:
```
** (MyXQL.Error) (1267) (ER_CANT_AGGREGATE_2COLLATIONS) Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```

**Comment by wojtekmach** [comment]
I cannot reproduce this error locally, could you create a minimal sample app or a test to this project?

Also, what myxql and mysql version are you using? If you're not using the latest myxql version, could you try upgrading?

**Comment by dbhobbs** [comment]
I've narrowed the issue down to a custom `Ecto.Type` that translates atoms into strings. I'm working on getting a sample project put together that can reproduce the issue.

**Comment by dbhobbs** [comment]
Our test suite is also failing with another custom `Ecto.Type` so maybe something changed in the way those custom types are used?

**Comment by josevalim** [comment]
Can you post the other Ecto type as well?

**Comment by dbhobbs** [comment]
I'm not able to reproduce the other custom type error in the sample app, so it may have a different underlying issue.

**Comment by dbhobbs** [comment]
I'd take a stab at fixing this, I just might need some guidance on where to start.

**Comment by wojtekmach** [comment]
@dbhobbs could you share your custom Ecto type that fails? (or ideally strip it down to a minimal version that fails). We are not able to reproduce this error locally and until we do I'm afraid there's nothing we can do.

Could you also post your myxql, ecto_sql, and mysql server versions?

**Comment by wojtekmach** [comment]
@dbhobbs apologies, I somehow missed that you already posted a sample project. I'm able to reproduce the issue locally, thank you.

**Comment by wojtekmach** [comment]
@dbhobbs ok, the bug is caused because we only use `:charset` and `:collation` options for creating the db, migrations etc, not when _connecting_ to the DB. Instead of supporting these options in MyXQL, we opted to have users set charset themselves by executing a query using an `:after_connect` option. Will need to revisit that choice.

A workaround for you in the meantime is to add `:after_connect` option in your repo config like the following:

```elixir
config :myxql_atom, MyxqlAtom.Repo,
  database: "testytest",
  username: "testytest",
  password: "testytest",
  hostname: "db",
  charset: "utf8mb4",
  collation: "utf8mb4_unicode_ci",
  pool: Ecto.Adapters.SQL.Sandbox,
  after_connect: fn conn ->
    MyXQL.query!(conn, "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'")
  end
```

thanks again for a way to reproduce this issue, let me know if the workaround works for you.

**Comment by dbhobbs** [comment]
Adding the `after_connect` option to the Repo configuration worked!

I did, however, need to add a semicolon to end the `SET NAMES` query.

Thanks!
