### ISSUE TITLE
JSON/map fields are only supported on MySQL 5.7.8 or later

### ISSUE THREAD

**Issue by 1player** [elixir-ecto/myxql#75]
I've just migrated from Mariaex, on a production app running MySQL 5.6.37.

This library says it's compatible with MySQL 5.5+ but myxql fails when creating a `map` field. mariaex uses a text field for those. MySQL added support for the JSON type in version 5.7.8

Probably you'll never support stringified JSON, but it might be a good idea to add a note in the README about it.

```
# mix ecto.migrate
** (MyXQL.Error) (1064) (ER_PARSE_ERROR) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL, `inserted_at` datetime NOT NULL, `updated_at` datetime NOT NULL, ' at line 1
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:166: :timer.tc/1
    (ecto_sql) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/7
    (ecto_sql) lib/ecto/migrator.ex:276: Ecto.Migrator.attempt/7
    (ecto_sql) lib/ecto/migrator.ex:177: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto_sql) lib/ecto/migrator.ex:254: Ecto.Migrator.run_maybe_in_transaction/6
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by wojtekmach** [comment]
Thank you for the report. As far as the driver is concerned, json is always returned as text on the protocol, so there's nothing to do here per se, but I agree we should try to document it somehow. I'll add a note about our json handling in the driver readme.

On the Ecto side, all you need to do is change in your migration:

    add :some_field, :map

to:

    add :some_field, :text

and it should work. Could you double-check? I'm not sure if we can come up with a nicer error message on Ecto side, but we should at least attempt to document it somehow there too.
