### ISSUE TITLE
Connection hanging in CLOSE_WAIT state

### ISSUE THREAD

**Issue by kovalpetro** [elixir-ecto/myxql#79]
The issue: When the `MyXQL.Client` tried to establish a connection to MySQL server with incorrect credentials (username or password) it creates a new connection, logs the error and tried to reconnect but does not close the opened connection. Which result in around 50000 opened TCP CLOSE_WAIT connections to MySQL server in one hour.
I've monitored connections by using next command:
`sudo lsof | grep mysql | grep -i close_wait | wc -l`

The issue is related to this part of code: https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/client.ex#L283

Suggested fix: 
Before returning error check if the connection exists and if it does - close it
```
{:ok, err_packet() = err_packet} ->
  if state.connection_id, do: sock_close(state)
  {:error, err_packet}
```

myxql version - 0.2.4
MySQL version - 5.6

**Comment by wojtekmach** [comment]
Thank you for the report, I couldn't reproduce this error locally but it definitely makes sense to close the socket on such errors.

Could you try branch `wm-disconnect`?

**Comment by kovalpetro** [comment]
@wojtekmach thanks for the update. I've just tried to reproduce the issue locally on the provided branch and it's gone. 
On reproducing the issue - have you tried to establish a connection directly in the console by calling `MyXQL.Client.connect()`?

**Comment by wojtekmach** [comment]
@kovalpetro yes, I tried that but no dice. But seems the branch fixes your error, so I'll ship that patch in next release.
