### ISSUE TITLE
Can't connect to MariaDB on Azure

### ISSUE THREAD

**Issue by olafmaas** [elixir-ecto/myxql#86]
Hi!

I am trying to connect to a MariaDB server on Azure. It seems that `myxql` has issues with the Azure layer. If I try to connect I get the following error message: 

```
[error] GenServer #PID<0.303.0> terminating
** (MyXQL.Error) (9999) () An internal error has occurred. Please retry or report your issues.
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: MyXQL.Connection
```

If I try to connect on a MariaDB instance on my local machine everything seems te be fine. Using the same credentials I'm able to login using a MySQL client and the mariaex driver.

**Comment by olafmaas** [comment]
Did some debugging and it seems to go wrong during the handshake. And espacially the authorization part. Azure expects their usernames to be `username@database_name` and will refuse to connect if the `@database_name`is not present. 

`An internal error has occurred. Please retry or report your issues.` seems to be the response of Azure in that case.

**Comment by wojtekmach** [comment]
I was able to connect via mysql cli to `*.mariadb.database.azure.com` but couldn't with myxql or mariaex. Could you double-check if you can connect to Azure with Mariaex? In any case, that's definitely a bug, thank you for the report.

**Comment by wojtekmach** [comment]
The fix is on master!
