### ISSUE TITLE
Too much open prepared statements

### ISSUE THREAD

**Issue by Gigitsu** [elixir-ecto/myxql#93]
I've just updated myxql version from `0.2.10` to  `0.3.0` and mysql `prepared_stmt_count` has begun to increment, reaching eventually the value of `max_prepared_stmt_count` (16000 by default).

Then the application were no longer able to execute queries because mysql won't accept any more prepared statements.

I'm using `phoenix ~> 1.4.10` with `phoenix_ecto ~> 4.0` and `ecto_sql ~> 3.1`.

**Comment by mattiaslundberg** [comment]
We're also seeing this issue after upgrading myxql from `0.2.10` to `0.3.0`.

Example error:
```
** (exit) %MyXQL.Error{connection_id: 20344319, message: "(1461) (ER_MAX_PREPARED_STMT_COUNT_REACHED) Can't create more than max_prepared_stmt_count statements (current value: 16382)", mysql: %{code: 1461, name: :ER_MAX_PREPARED_STMT_COUNT_REACHED}, statement: "SELECT <intentionally removed>"}
```

Happy to provide more details if needed!

**Comment by wojtekmach** [comment]
Thank you for the report, I reverted a [commit](https://github.com/elixir-ecto/myxql/commit/ed3067ebaf10d5c67fb4e1ee9f77d4291528d687) that was the likely regression and shipped v0.3.1 so that should unblock you.

**Comment by josevalim** [comment]
Hi @Gigitsu and @mattiaslundberg, can you please answer the following questions:

 * Are you setting `prepare: :unnamed` by any chance? If possible, can you share your repository configuration (no need to include password)

 * How much time does it take for the issue to appear after a new deploy? Minutes? Hours?

 * Are you using Repo.stream in your application?

 * When the error happens, does the application still work for a while, until the error happens again? Or does it never work ever again?

**Comment by Gigitsu** [comment]
> * Are you setting `prepare: :unnamed` by any chance? If possible, can you share your repository configuration (no need to include password)

No, I double checked that settings and I don't explicitly set `prepare: :unnamed` anywhere.
This is my original configuration:
```
config :myapp, MyModel.Repo,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASSWORD"),
  database: System.get_env("DB_NAME"),
  hostname: System.get_env("DB_HOST"),
  pool_size: String.to_integer(System.get_env("DB_POOL_SIZE") || "10")
```

Then I've also tried adding this:
```
config :myapp, MyModel.Repo, prepare: :named
```

but in both cases I always, eventually, get the error.





> * How much time does it take for the issue to appear after a new deploy? Minutes? Hours?

I don't know exactly but in my last test, in about an hour after a new deploy, the open prepared statements count has reached  ~1000.

> * Are you using Repo.stream in your application?

No


> * When the error happens, does the application still work for a while, until the error happens again? Or does it never work ever again?

It does never work ever again, I need to restart it. When the application is stopped, the open statements
drops to 0.

**Comment by mattiaslundberg** [comment]
> Are you setting prepare: :unnamed by any chance? If possible, can you share your repository configuration (no need to include password)

Not  setting `prepare: :unnamed`, here is the relevant config:

```elixir
config :app, App.Repo, url: System.fetch_env!("DB_URL")
config :app, App.Repo,
  charset: "utf8mb4",
  after_connect: {App.Repo, :after_connect, []}

defmodule App.Repo do
  use Ecto.Repo, otp_app: :app, adapter: Ecto.Adapters.MyXQL

  def after_connect(conn) do
    MyXQL.query!(conn, "SET SESSION SQL_MODE=STRICT_TRANS_TABLES")
    MyXQL.query!(conn, "SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED")
    MyXQL.query!(conn, "SET character_set_client = utf8mb4")
    MyXQL.query!(conn, "SET character_set_results = utf8mb4")
    MyXQL.query!(conn, "SET character_set_connection = utf8mb4")
  end
end
```

> How much time does it take for the issue to appear after a new deploy? Minutes? Hours?

About 1 hour.

> Are you using Repo.stream in your application?

No.

> When the error happens, does the application still work for a while, until the error happens again? Or does it never work ever again?

Not sure, running on k8s and the only thing we can see is that the pods die, from the logs it looks like the erlang processes crashes leading to the full vm shuting down resulting in released statements and a new pod running (and working for a while).
