### ISSUE TITLE
no function clause matching in MyXQL.Protocol.Values.decode_time/4

### ISSUE THREAD

**Issue by kwando** [elixir-ecto/myxql#95]
```
[error] GenServer #PID<0.4983.0> terminating
** (DBConnection.ConnectionError) client #PID<0.5091.0> stopped: ** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.decode_time/4
    (myxql) lib/myxql/protocol/values.ex:459: MyXQL.Protocol.Values.decode_time(<<8, 1, 0, 0, 0, 0, 0, 0, 1, 255, 255, 255, 255, 255, 255, 255, 255>>, 0, [:int8], [~U[2020-01-08 13:12:55Z], 1, 13201, "One Account ", "Some String", 5230322])
    (myxql) lib/myxql/protocol.ex:535: MyXQL.Protocol.decode_resultset/4
    (myxql) lib/myxql/client.ex:194: MyXQL.Client.recv_packets/5
    (myxql) lib/myxql/connection.ex:102: MyXQL.Connection.handle_execute/4
    (db_connection) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
    (db_connection) lib/db_connection.ex:532: DBConnection.prepare_execute/4
    (myxql) lib/myxql.ex:234: MyXQL.do_query/4
```

This is using MyXQL 0.3.1 with an acient version of MySQL (5.5.49-0ubuntu0.14.04.1-log)

**Comment by wojtekmach** [comment]
Thank you for your report. I'm able to reproduce this as follows:

```elixir
# positive time
iex> MyXQL.query!(pid, "SELECT TIME(ADDTIME('00:00:00', '00:00:01'));").rows
[[~T[00:00:01]]]

# negative time
iex> MyXQL.query!(pid, "SELECT TIME(SUBTIME('00:00:00', '00:00:01'));").rows
** (DBConnection.ConnectionError) client #PID<0.2481.0> stopped: ** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.decode_time/4
    (myxql 0.3.1) lib/myxql/protocol/values.ex:459: MyXQL.Protocol.Values.decode_time(<<8, 1, 0, 0, 0, 0, 0, 0, 1>>, 0, [], [])
```

Even though MySQL protocol supports negative time values, Elixir does not and so I'm afraid there's nothing we can do about that. I'll improve the error message and document this.

**Comment by kwando** [comment]
Thanks for having a look, in my case I can clamp values to 00:00:00 (now that I know that was the problem).

I guess there will be a similar issue with "times larger than 24 hours" too then.

**Comment by wojtekmach** [comment]
> I guess there will be a similar issue with "times larger than 24 hours" too then.

that's a very good point, we need to handle that too.

**Comment by byronpc** [comment]
can you please help me with this...i'm also getting this error on a couple of queries (but it's hard to pinpoint which queries they are) as the stack doesn't include our own library

MyXQL.Protocol.Values.decode_time(<<8, 0, 14, 0, 0, 0, 15, 2, 20>>, 0, [], [4397573])
MyXQL.Protocol.Values.decode_time(<<8, 0, 13, 0, 0, 0, 15, 49, 15>>, 0, [], [4397597])
MyXQL.Protocol.Values.decode_time(<<8, 0, 14, 0, 0, 0, 15, 2, 20>>, 0, [], [4397573])

these are sample queries where the decode_time failed
