### ISSUE TITLE
Extremely slow test on ci runner

### ISSUE THREAD

**Issue by nulian** [elixir-ecto/myxql#98]
I'm trying to upgrade ecto and to myxql but for some reason on the ci runner the tests are extremely slow like 10x slower then normal. 

Running test locally they perform fine with the ecto upgrade.

All the queries have around 40 ms delay like below. So originally I thought it's maybe because of the CI server not having the unix socket and it takes myxql some time to fallback. But even when setting protocol in test config for ecto on :tcp it still has the around 40 ms delay on everything.
`QUERY OK source="applications" db=39.9ms`
`QUERY OK db=0.4ms queue=40.3ms`

It's a kubernetes gitlab ci runner with mysql running a connected service.
With like the following ecto config
```
config :synapse, Synapse.Repo,
  username: "root",
  password: "",
  database: "synapse_test",
  hostname: "127.0.0.1",
  pool: Ecto.Adapters.SQL.Sandbox,
  charset: "utf8",
  collation: "utf8_general_ci",
  protocol: :tcp,
  prepare: :unnamed
```

**Comment by wojtekmach** [comment]
Could you paste the exact version numbers of ecto_sql and myxql you tried?

**Comment by nulian** [comment]
ecto 3.3.1
ecto_sql 3.3.2
db_connection 2.2.0

**Comment by wojtekmach** [comment]
what's your myxql version?

**Comment by nulian** [comment]
0.3.1

**Comment by deepfryed** [comment]
@nulian do they run faster if you use named prepared statements ? We're investigating a similar issue with 0.3.2 where tests are 4-5x slower with unnamed prepare.

**Comment by nulian** [comment]
It does seem to fix test performance removing the unnamed statement flag. 
So I could do that to improve test performance. A bit weird that on my local machine I didn't have the big penalty but the test server did.
Running it again with the unnamed flag enabled to be sure nothing else changed in the month.

**Comment by nulian** [comment]
Retested them.

Mariaex test run: 31.5s
Myxql without unnamed option: 42.7s
Myxql with unnamed option: 398.2s

**Comment by melpon** [comment]
I encountered the same problem, but it was solved by setting `nodelay: true`. 

```
config :synapse, Synapse.Repo,
  ...
  prepare: :unnamed,
  socket_options: [nodelay: true]
```

However, I didn't know why this option isn't needed in mariaex.

**Comment by lucas-nelson** [comment]
Thank you @melpon! That change got our test exection time back down to where it should be.

**Comment by 0xAX** [comment]
re-checked just for the case:

I've set pool_size of my Repo configuration to `1` to be sure that everything is related to one connection and executed:

```
Tposs.Repo.insert(%MyModel{name: "test_1", field_id: nil})
Tposs.Repo.insert(%MyModel{name: "test_2", field_id: "test"})
Tposs.Repo.insert(%MyModel{name: "test_3", field_id: nil})
```

and I see following queries were sent to my db:

[
![myxql-prepared-statements](https://user-images.githubusercontent.com/2699235/136579292-23a8f515-a7c3-45e2-b699-2433880d8a86.png)
](url)

is it expected behaviour?

**Comment by josevalim** [comment]
I see. So it is nothing to change here. The issue is that we are using the same name for different queries. If you change this line:

https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/myxql.ex#L259

To be:

    opts = [{:cache_statement, "ecto_insert_#{source}_#{length(fields)}"} | opts]

It should introduce another degree of caching. Another option is to emit all fields and have the value be `DEFAULT`, this would keep the query the same.

**Comment by nulian** [comment]
Weird I had that same delay issue trigger on linux dev environment after installing updates. Which I could solve with the nodelay: true.
No clue why my dev environment suddenly needed that option because before it was fast.

**Comment by josevalim** [comment]
Closing this. It is stale and it may even have been fixed in Ecto (it has been a while, so I don’t fully remember).
